
--PHASE-1
CREATE WAREHOUSE IF NOT EXISTS ENTERPRISE_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ENTERPRISE_DB;

CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DB.SALES_SCHEMA;

USE WAREHOUSE ENTERPRISE_WH;

USE DATABASE ENTERPRISE_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null');

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @SALES_STAGE;



--PHASE2
CREATE OR REPLACE TABLE CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE OR REPLACE TABLE PRODUCTS
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE BRANCHES
(
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    STATE VARCHAR
);

CREATE OR REPLACE TABLE SALES
(
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    QUANTITY NUMBER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

CREATE OR REPLACE TABLE NEW_SALES_STAGE
(
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    QUANTITY NUMBER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM CUSTOMERS
ORDER BY CUSTOMER_ID;

COPY INTO PRODUCTS
FROM @SALES_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM PRODUCTS
ORDER BY PRODUCT_ID;

COPY INTO BRANCHES
FROM @SALES_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM BRANCHES
ORDER BY BRANCH_ID;

COPY INTO SALES
FROM @SALES_STAGE/sales_history.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM SALES
ORDER BY SALE_ID;

SELECT COUNT(*) AS HISTORICAL_SALES_COUNT
FROM SALES;



--PHASE-3
CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES;

COPY INTO NEW_SALES_STAGE
FROM @SALES_STAGE/new_sales.csv
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT *
FROM NEW_SALES_STAGE
ORDER BY SALE_ID;

INSERT INTO SALES
(
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
FROM NEW_SALES_STAGE;

SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM SALES_STREAM
WHERE METADATA$ACTION = 'INSERT'
ORDER BY SALE_ID;

MERGE INTO SALES AS TARGET
USING
(
    SELECT
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    FROM NEW_SALES_STAGE
) AS SOURCE
ON TARGET.SALE_ID = SOURCE.SALE_ID

WHEN NOT MATCHED THEN

INSERT
(
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)

VALUES
(
    SOURCE.SALE_ID,
    SOURCE.CUSTOMER_ID,
    SOURCE.PRODUCT_ID,
    SOURCE.BRANCH_ID,
    SOURCE.QUANTITY,
    SOURCE.SALE_DATE,
    SOURCE.TOTAL_AMOUNT
);

SELECT *
FROM SALES
ORDER BY SALE_ID;



--PHASE-4
SELECT
    SALE_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1
ORDER BY SALE_ID;

SELECT
    S.SALE_ID,
    S.CUSTOMER_ID
FROM SALES S
LEFT JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.CUSTOMER_ID IS NULL
ORDER BY S.SALE_ID;

SELECT
    S.SALE_ID,
    S.PRODUCT_ID
FROM SALES S
LEFT JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL
ORDER BY S.SALE_ID;

SELECT
    S.SALE_ID,
    S.BRANCH_ID
FROM SALES S
LEFT JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID
WHERE B.BRANCH_ID IS NULL
ORDER BY S.SALE_ID;

SELECT COUNT(*) AS TOTAL_NEW_RECORDS
FROM NEW_SALES_STAGE;




--PHASE-5
DELETE FROM SALES
WHERE SALE_ID = 9;

SELECT *
FROM SALES
WHERE SALE_ID = 9;

SELECT *
FROM SALES
AT (OFFSET => -180)
WHERE SALE_ID = 9;


INSERT INTO SALES
SELECT *
FROM SALES
AT (OFFSET => -180)
WHERE SALE_ID = 9;

SELECT *
FROM SALES
WHERE SALE_ID = 9;

--PHASE-6
CREATE OR REPLACE TABLE SALES_TEST
CLONE SALES;

SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

INSERT INTO SALES_TEST
VALUES (
    11,
    1,
    103,
    1,
    3,
    '2026-07-11',
    4500
);


SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

SELECT *
FROM SALES
ORDER BY SALE_ID;

CREATE OR REPLACE TASK DAILY_INCREMENTAL_LOAD
WAREHOUSE = ENTERPRISE_WH
SCHEDULE = 'USING CRON 0 1 * * * UTC'
AS
MERGE INTO SALES AS TARGET
USING NEW_SALES_STAGE AS SOURCE
ON TARGET.SALE_ID = SOURCE.SALE_ID

WHEN MATCHED THEN
    UPDATE SET
        TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
        TARGET.PRODUCT_ID = SOURCE.PRODUCT_ID,
        TARGET.BRANCH_ID = SOURCE.BRANCH_ID,
        TARGET.QUANTITY = SOURCE.QUANTITY,
        TARGET.SALE_DATE = SOURCE.SALE_DATE,
        TARGET.TOTAL_AMOUNT = SOURCE.TOTAL_AMOUNT

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        SOURCE.SALE_ID,
        SOURCE.CUSTOMER_ID,
        SOURCE.PRODUCT_ID,
        SOURCE.BRANCH_ID,
        SOURCE.QUANTITY,
        SOURCE.SALE_DATE,
        SOURCE.TOTAL_AMOUNT
    );

ALTER TASK DAILY_INCREMENTAL_LOAD
RESUME;

SHOW TASKS;

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'DAILY_INCREMENTAL_LOAD'
    )
);

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN BRANCHES b
    ON s.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN PRODUCTS p
    ON s.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS MONTH,
    SUM(TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY MONTH;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN BRANCHES b
    ON s.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN PRODUCTS p
    ON s.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;


SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(s.SALE_ID) AS PURCHASE_FREQUENCY
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY PURCHASE_FREQUENCY DESC;

SELECT
    SALE_DATE,
    SALE_ID,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS RUNNING_REVENUE
FROM SALES
ORDER BY SALE_DATE, SALE_ID;


SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE,

    RANK() OVER (
        ORDER BY SUM(s.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK

FROM SALES s
JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID

GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME

ORDER BY CUSTOMER_RANK;


CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES s
JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME;


SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

CREATE OR REPLACE MATERIALIZED VIEW BRANCH_REVENUE AS
SELECT
    BRANCH_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY BRANCH_ID;


SELECT *
FROM BRANCH_REVENUE;

SELECT
    br.BRANCH_ID,
    b.BRANCH_NAME,
    br.TOTAL_REVENUE
FROM BRANCH_REVENUE br
JOIN BRANCHES b
    ON br.BRANCH_ID = b.BRANCH_ID
ORDER BY br.TOTAL_REVENUE DESC;