CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL_DB.RETAIL_SCHEMA;

USE WAREHOUSE RETAIL_WH;

USE DATABASE RETAIL_DB;

USE SCHEMA RETAIL_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_STAGE;

CREATE OR REPLACE TABLE CUSTOMERS_RAW
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE OR REPLACE TABLE PRODUCTS_RAW
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    BRAND VARCHAR,
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE BRANCHES_RAW
(
    BRANCH_ID NUMBER,
    BRANCH_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    MANAGER_NAME VARCHAR
);

CREATE OR REPLACE TABLE CALENDAR_RAW
(
    DATE_ID NUMBER,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    WEEK_NO NUMBER,
    MONTH VARCHAR,
    QUARTER VARCHAR,
    YEAR NUMBER,
    IS_WEEKEND VARCHAR
);

CREATE OR REPLACE TABLE SALES_RAW
(
    SALE_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO CUSTOMERS_RAW
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO PRODUCTS_RAW
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRANCHES_RAW
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO CALENDAR_RAW
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO SALES_RAW
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE OR REPLACE TABLE DIM_PRODUCT
(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    BRAND VARCHAR,
    PRICE NUMBER(12,2)
);

    CREATE OR REPLACE TABLE DIM_BRANCH
(
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    REGION VARCHAR,
    MANAGER_NAME VARCHAR
);

CREATE OR REPLACE TABLE DIM_DATE
(
    DATE_ID NUMBER PRIMARY KEY,
    DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    WEEK_NO NUMBER,
    MONTH VARCHAR,
    QUARTER VARCHAR,
    YEAR NUMBER,
    IS_WEEKEND VARCHAR
);

INSERT INTO DIM_CUSTOMER
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM CUSTOMERS_RAW;

INSERT INTO DIM_PRODUCT
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    PRICE
FROM PRODUCTS_RAW;

INSERT INTO DIM_BRANCH
SELECT
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION,
    MANAGER_NAME
FROM BRANCHES_RAW;

INSERT INTO DIM_DATE
SELECT
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
FROM CALENDAR_RAW;

CREATE OR REPLACE TABLE FACT_SALES
(
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES DIM_BRANCH(BRANCH_ID),
    FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
);

INSERT INTO FACT_SALES
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM SALES_RAW;

SELECT * FROM DIM_CUSTOMER;

SELECT * FROM DIM_PRODUCT;

SELECT * FROM DIM_BRANCH;

SELECT * FROM DIM_DATE;

SELECT * FROM FACT_SALES;

SELECT COUNT(*) AS COUNT
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS COUNT
FROM DIM_PRODUCT;

SELECT COUNT(*) AS COUNT
FROM DIM_BRANCH;

SELECT COUNT(*) AS COUNT
FROM DIM_DATE;

SELECT COUNT(*) AS COUNT
FROM FACT_SALES;

SELECT
    F.SALE_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    B.BRANCH_NAME,
    D.DATE,
    F.QUANTITY,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID;


SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    B.STATE,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.STATE
ORDER BY TOTAL_SALES DESC;

SELECT
    D.YEAR,
    D.MONTH,
    SUM(F.TOTAL_AMOUNT) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.MONTH
ORDER BY
    D.YEAR,
    MIN(D.DATE);

SELECT
    D.YEAR,
    D.QUARTER,
    SUM(F.TOTAL_AMOUNT) AS QUARTERLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    D.YEAR,
    D.QUARTER
ORDER BY
    D.YEAR,
    D.QUARTER;

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT
    P.CATEGORY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT
    C.CUSTOMER_NAME,
    D.DATE,
    SUM(F.QUANTITY) AS QUANTITY_PURCHASED,
    SUM(F.TOTAL_AMOUNT) AS PURCHASE_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY
    C.CUSTOMER_NAME,
    D.DATE
ORDER BY
    C.CUSTOMER_NAME,
    D.DATE;

SELECT
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND
ORDER BY REVENUE DESC;

SELECT
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    B.REGION,
    SUM(F.QUANTITY) AS UNITS_SOLD,
    SUM(F.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY
    B.BRANCH_NAME,
    B.CITY,
    B.STATE,
    B.REGION
ORDER BY REVENUE DESC;

SELECT
    B.REGION,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
GROUP BY B.REGION
ORDER BY TOTAL_SALES DESC;


SELECT
    D.DATE,
    SUM(F.QUANTITY) AS TOTAL_QUANTITY,
    SUM(F.TOTAL_AMOUNT) AS TOTAL_SALES
FROM FACT_SALES F
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
GROUP BY D.DATE
ORDER BY D.DATE;

SELECT
    F.SALE_ID,
    C.CUSTOMER_NAME,
    C.STATE AS CUSTOMER_STATE,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    B.BRANCH_NAME,
    B.STATE AS BRANCH_STATE,
    B.REGION,
    D.DATE,
    D.MONTH,
    D.QUARTER,
    D.YEAR,
    F.QUANTITY,
    F.TOTAL_AMOUNT
FROM FACT_SALES F
JOIN DIM_CUSTOMER C
    ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON F.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON F.DATE_ID = D.DATE_ID
ORDER BY F.SALE_ID;